CREATE TABLE RAW_FOOD_DATA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    energy_100g FLOAT,
    fat_100g FLOAT,
    carbohydrates_100g FLOAT,
    sugars_100g FLOAT,
    proteins_100g FLOAT,
    salt_100g FLOAT
);

-- Тестовые данные (Insert)
INSERT INTO RAW_FOOD_DATA (energy_100g, fat_100g, carbohydrates_100g, sugars_100g, proteins_100g, salt_100g)
VALUES (2000, 10.5, 50.0, 5.0, 8.0, 1.2);
INSERT INTO RAW_FOOD_DATA (energy_100g, fat_100g, carbohydrates_100g, sugars_100g, proteins_100g, salt_100g)
VALUES (150, 0.5, 3.0, 2.0, 1.0, 0.1);
COMMIT;